Upgrade to laravel 8
obiefy/api-response pull request #42
Opened 2020-09-24 19:19 UTC by khatabwedaa

### Update
- laravel illuminate support
- phpunit
- testbench
### Change 
- `array_key_exists()` to `property_exists`

2020-10-04 20:00 UTC, beauraines commented
@khatabwedaa I decided to upgrade one of my projects to Laravel 8 and was glad to find your PR. Thank for this. The changes seem to work, but I know that @obiefy also relies on the StyleCI checks. From the details link on the StyleCI failure, you can download a diff that will make it pass the style checks.  Download that file and apply them `git apply <downloaded_filename>` and we should be golden.

It's passing the tests, too. I applied the StyleCI fixes in my branch 1d8886c

```
Beaus-MacBook-Pro:api-response beauraines$ git log -7 --oneline
1d8886c (HEAD -> upgrade-to-laravel-8, origin/upgrade-to-laravel-8) Applies StyleCI fixes
7b60b2b wip
0c11002 Chane array_key_exists() to property_exists()
fc79ffd Update composer.json
d05cb84 Add composer.lock to gitignore
aa95b94 (tag: v0.9.1, upstream/master, master) Merge pull request #38 from obiefy/Status-Improvements
a655d59 (upstream/Status-Improvements) Merge pull request #39 from obiefy/analysis-OMbpmP
Beaus-MacBook-Pro:api-response beauraines$ phpunit
PHPUnit 8.3.4 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.10
Configuration: /Users/beauraines/projects/api-response/phpunit.xml

..........................                                        26 / 26 (100%)

Time: 233 ms, Memory: 12.00 MB

OK (26 tests, 31 assertions)
Beaus-MacBook-Pro:api-response beauraines$
```

2020-10-04 20:37 UTC, khatabwedaa commented
Hello, thanks @beauraines I did not check the CI result because all the tests work great in local, Fix it, and now it passes CI tests thanks again 😎.

2020-10-14 15:49 UTC, obiefy requested changes
Hi @khatabwedaa, thanks for this PR, and I apologize for the late response.
Kindly check my recent comments, and I'll merge the PR once you applied the changes.
Thanks :)

2020-10-14 15:49 UTC, obiefy commented on composer.json
> +        "illuminate/support": "^8.0"
Hi @khatabwedaa, can you please keep the old versions and add `^8.0` as an additional version? 
Cause this will break old versions support.

2020-10-14 16:51 UTC, khatabwedaa commented
> Hi @khatabwedaa, thanks for this PR, and I apologize for the late response.
> Kindly check my recent comments, and I'll merge the PR once you applied the changes.
> Thanks :)

@obiefy Done

2020-10-14 16:54 UTC, obiefy approved these changes

2020-10-14 16:54 UTC, merged

2020-10-14 16:55 UTC, obiefy commented
Thanks, @khatabwedaa :)